export type QuickStartSection = {
  title: string;
  defaultItems: string[];
  allItems: string[];
};

export const QUICK_START_SECTIONS: QuickStartSection[] = [
  {
    title: "Proteins",
    defaultItems: ["chicken", "beef", "eggs"],
    allItems: [
      "chicken",
      "chicken breast",
      "chicken thighs",
      "chicken tenderloins",
      "beef",
      "ground beef",
      "steak",
      "beef strips",
      "pork chops",
      "pork tenderloin",
      "ground turkey",
      "turkey breast",
      "sausage",
      "bacon",
      "ham",
      "shrimp",
      "salmon",
      "white fish",
      "tilapia",
      "tuna",
      "eggs",
      "tofu",
      "canned beans",
      "cooked beans",
      "lentils",
    ],
  },
  {
    title: "Carbs",
    defaultItems: ["rice", "pasta", "bread"],
    allItems: [
      "rice",
      "pasta",
      "spaghetti",
      "linguine",
      "fettuccine",
      "egg noodles",
      "macaroni",
      "shells",
      "penne",
      "bread",
      "burger buns",
      "sandwich rolls",
      "tortillas",
      "potatoes",
      "sweet potatoes",
      "breadcrumbs",
      "flour",
      "cornmeal",
      "oats",
      "quinoa",
      "couscous",
    ],
  },
  {
    title: "Basics",
    defaultItems: ["milk", "butter", "cheese"],
    allItems: [
      "milk",
      "heavy cream",
      "half-and-half",
      "butter",
      "sour cream",
      "cream cheese",
      "plain yogurt",
      "cheese",
      "shredded cheddar",
      "shredded mozzarella",
      "mixed cheese",
      "parmesan",
      "sliced cheese",
    ],
  },
  {
    title: "Vegetables",
    defaultItems: ["onion", "tomato", "spinach"],
    allItems: [
      "onion",
      "red onion",
      "yellow onion",
      "white onion",
      "green onion",
      "scallions",
      "garlic",
      "bell peppers",
      "jalapenos",
      "carrots",
      "celery",
      "broccoli",
      "cauliflower",
      "spinach",
      "kale",
      "lettuce",
      "romaine",
      "cabbage",
      "zucchini",
      "squash",
      "mushrooms",
      "tomato",
      "cherry tomatoes",
      "grape tomatoes",
      "cucumbers",
      "corn",
      "peas",
      "green beans",
      "asparagus",
      "avocado",
      "lemons",
      "limes",
    ],
  },
  {
    title: "Canned & Jarred",
    defaultItems: ["broth", "tomato sauce", "pasta sauce"],
    allItems: [
      "broth",
      "chicken broth",
      "beef broth",
      "vegetable broth",
      "tomato sauce",
      "crushed tomatoes",
      "diced tomatoes",
      "tomato paste",
      "coconut milk",
      "pasta sauce",
      "salsa",
      "peanut butter",
      "jam",
      "jelly",
    ],
  },
  {
    title: "Pantry",
    defaultItems: ["oil", "soy sauce", "sugar"],
    allItems: [
      "oil",
      "olive oil",
      "vinegar",
      "soy sauce",
      "worcestershire",
      "hot sauce",
      "mustard",
      "mayo",
      "ketchup",
      "sugar",
      "brown sugar",
      "honey",
    ],
  },
  {
    title: "Seasonings",
    defaultItems: ["salt", "black pepper", "garlic powder"],
    allItems: [
      "salt",
      "black pepper",
      "garlic powder",
      "onion powder",
      "paprika",
      "italian seasoning",
      "chili powder",
      "cumin",
      "red pepper flakes",
    ],
  },
];

export const QUICK_START_ITEMS = Array.from(
  new Set(QUICK_START_SECTIONS.flatMap((section) => section.allItems)),
);
