// This file is generated by tools/generate-ingredient-taxonomy.cjs.
// Do not edit by hand; update the backend catalog or generator compatibility config instead.

export const GENERATED_INGREDIENT_BROWSE_NODES = [
  {
    "id": "chicken",
    "label": "Chicken & poultry",
    "categoryId": "proteins",
    "subcategoryId": "poultry",
    "aliases": [
      "chicken"
    ],
    "visibleInBrowser": true,
    "visibleInQuickPick": true,
    "recommendationRollupIds": [
      "chicken"
    ]
  },
  {
    "id": "beef",
    "label": "Beef",
    "categoryId": "proteins",
    "subcategoryId": "red_meat",
    "aliases": [],
    "visibleInBrowser": true,
    "visibleInQuickPick": true,
    "recommendationRollupIds": [
      "beef"
    ]
  },
  {
    "id": "pork",
    "label": "Pork",
    "categoryId": "proteins",
    "subcategoryId": "red_meat",
    "aliases": [],
    "visibleInBrowser": true,
    "visibleInQuickPick": false,
    "recommendationRollupIds": [
      "pork"
    ]
  },
  {
    "id": "seafood",
    "label": "Seafood",
    "categoryId": "proteins",
    "subcategoryId": "seafood",
    "aliases": [
      "fish"
    ],
    "visibleInBrowser": true,
    "visibleInQuickPick": false,
    "recommendationRollupIds": [
      "seafood"
    ]
  },
  {
    "id": "beans_legumes",
    "label": "Beans & legumes",
    "categoryId": "proteins",
    "subcategoryId": "plant_protein",
    "aliases": [
      "beans"
    ],
    "visibleInBrowser": true,
    "visibleInQuickPick": false,
    "recommendationRollupIds": [
      "plant_protein"
    ]
  },
  {
    "id": "tofu_plant_protein",
    "label": "Tofu & plant protein",
    "categoryId": "proteins",
    "subcategoryId": "plant_protein",
    "aliases": [
      "tofu"
    ],
    "visibleInBrowser": true,
    "visibleInQuickPick": false,
    "recommendationRollupIds": [
      "plant_protein"
    ]
  },
  {
    "id": "eggs",
    "label": "Eggs",
    "categoryId": "proteins",
    "subcategoryId": "eggs",
    "aliases": [
      "egg"
    ],
    "visibleInBrowser": true,
    "visibleInQuickPick": true,
    "recommendationRollupIds": [
      "eggs"
    ]
  },
  {
    "id": "rice_grains",
    "label": "Rice & grains",
    "categoryId": "grains_starches",
    "subcategoryId": "grains",
    "aliases": [],
    "visibleInBrowser": true,
    "visibleInQuickPick": true,
    "recommendationRollupIds": [
      "grains_starches"
    ]
  },
  {
    "id": "pasta_noodles",
    "label": "Pasta & noodles",
    "categoryId": "grains_starches",
    "subcategoryId": "pasta_noodles",
    "aliases": [],
    "visibleInBrowser": true,
    "visibleInQuickPick": true,
    "recommendationRollupIds": [
      "grains_starches"
    ]
  },
  {
    "id": "bread_wraps",
    "label": "Bread & wraps",
    "categoryId": "grains_starches",
    "subcategoryId": "bread_wraps",
    "aliases": [],
    "visibleInBrowser": true,
    "visibleInQuickPick": true,
    "recommendationRollupIds": [
      "grains_starches"
    ]
  },
  {
    "id": "potatoes",
    "label": "Potatoes",
    "categoryId": "grains_starches",
    "subcategoryId": "starches",
    "aliases": [],
    "visibleInBrowser": true,
    "visibleInQuickPick": false,
    "recommendationRollupIds": [
      "grains_starches"
    ]
  },
  {
    "id": "aromatics",
    "label": "Aromatics",
    "categoryId": "vegetables",
    "subcategoryId": "aromatics",
    "aliases": [],
    "visibleInBrowser": true,
    "visibleInQuickPick": true,
    "recommendationRollupIds": [
      "vegetables"
    ]
  },
  {
    "id": "peppers_chiles",
    "label": "Peppers & chiles",
    "categoryId": "vegetables",
    "subcategoryId": "peppers",
    "aliases": [],
    "visibleInBrowser": true,
    "visibleInQuickPick": false,
    "recommendationRollupIds": [
      "vegetables"
    ]
  },
  {
    "id": "leafy_greens",
    "label": "Leafy greens",
    "categoryId": "vegetables",
    "subcategoryId": "greens",
    "aliases": [],
    "visibleInBrowser": true,
    "visibleInQuickPick": true,
    "recommendationRollupIds": [
      "vegetables"
    ]
  },
  {
    "id": "brassicas",
    "label": "Brassicas",
    "categoryId": "vegetables",
    "subcategoryId": "brassicas",
    "aliases": [],
    "visibleInBrowser": true,
    "visibleInQuickPick": false,
    "recommendationRollupIds": [
      "vegetables"
    ]
  },
  {
    "id": "tomatoes",
    "label": "Tomatoes",
    "categoryId": "vegetables",
    "subcategoryId": "tomatoes",
    "aliases": [],
    "visibleInBrowser": true,
    "visibleInQuickPick": true,
    "recommendationRollupIds": [
      "vegetables"
    ]
  },
  {
    "id": "mushrooms",
    "label": "Mushrooms",
    "categoryId": "vegetables",
    "subcategoryId": "mushrooms",
    "aliases": [],
    "visibleInBrowser": true,
    "visibleInQuickPick": false,
    "recommendationRollupIds": [
      "vegetables"
    ]
  },
  {
    "id": "cheese",
    "label": "Cheese",
    "categoryId": "dairy_creamy",
    "subcategoryId": "cheese",
    "aliases": [],
    "visibleInBrowser": true,
    "visibleInQuickPick": true,
    "recommendationRollupIds": [
      "dairy_creamy"
    ]
  },
  {
    "id": "milk_cream",
    "label": "Milk / cream",
    "categoryId": "dairy_creamy",
    "subcategoryId": "milk_cream",
    "aliases": [],
    "visibleInBrowser": true,
    "visibleInQuickPick": true,
    "recommendationRollupIds": [
      "dairy_creamy"
    ]
  },
  {
    "id": "fresh_herbs",
    "label": "Fresh herbs",
    "categoryId": "herbs_spices",
    "subcategoryId": "fresh_herbs",
    "aliases": [],
    "visibleInBrowser": true,
    "visibleInQuickPick": false,
    "recommendationRollupIds": [
      "herbs_spices"
    ]
  },
  {
    "id": "dry_spices",
    "label": "Dry spices",
    "categoryId": "herbs_spices",
    "subcategoryId": "dry_spices",
    "aliases": [],
    "visibleInBrowser": true,
    "visibleInQuickPick": true,
    "recommendationRollupIds": [
      "herbs_spices"
    ]
  },
  {
    "id": "sauces",
    "label": "Sauces",
    "categoryId": "sauces_condiments",
    "subcategoryId": "sauces",
    "aliases": [],
    "visibleInBrowser": true,
    "visibleInQuickPick": true,
    "recommendationRollupIds": [
      "sauces_condiments"
    ]
  },
  {
    "id": "oils_fats",
    "label": "Oils & fats",
    "categoryId": "sauces_condiments",
    "subcategoryId": "oils_fats",
    "aliases": [],
    "visibleInBrowser": true,
    "visibleInQuickPick": true,
    "recommendationRollupIds": [
      "oils_fats"
    ]
  },
  {
    "id": "citrus",
    "label": "Citrus",
    "categoryId": "vegetables",
    "subcategoryId": "citrus",
    "aliases": [],
    "visibleInBrowser": true,
    "visibleInQuickPick": false,
    "recommendationRollupIds": [
      "citrus"
    ]
  },
  {
    "id": "regional_sauces_pastes",
    "label": "Regional sauces & pastes",
    "categoryId": "sauces_condiments",
    "subcategoryId": "regional_sauces",
    "aliases": [],
    "visibleInBrowser": true,
    "visibleInQuickPick": false,
    "recommendationRollupIds": [
      "regional_sauces_pastes"
    ]
  }
] as const;

export const GENERATED_INGREDIENT_BROWSE_FAMILY_GROUPS = [
  {
    "id": "proteins",
    "label": "Proteins",
    "nodeIds": [
      "chicken",
      "beef",
      "pork",
      "seafood",
      "eggs"
    ]
  },
  {
    "id": "beans_legumes",
    "label": "Beans & legumes",
    "nodeIds": [
      "beans_legumes",
      "tofu_plant_protein"
    ]
  },
  {
    "id": "grains_starches",
    "label": "Grains, pasta & starches",
    "nodeIds": [
      "rice_grains",
      "pasta_noodles",
      "bread_wraps",
      "potatoes"
    ]
  },
  {
    "id": "vegetables",
    "label": "Vegetables",
    "nodeIds": [
      "aromatics",
      "peppers_chiles",
      "leafy_greens",
      "brassicas",
      "tomatoes",
      "mushrooms"
    ]
  },
  {
    "id": "dairy",
    "label": "Dairy",
    "nodeIds": [
      "cheese",
      "milk_cream"
    ]
  },
  {
    "id": "oils_fats",
    "label": "Oils & fats",
    "nodeIds": [
      "oils_fats"
    ]
  },
  {
    "id": "sauces_condiments",
    "label": "Sauces & condiments",
    "nodeIds": [
      "sauces",
      "regional_sauces_pastes"
    ]
  },
  {
    "id": "pantry_basics",
    "label": "Pantry basics",
    "nodeIds": [
      "dry_spices",
      "fresh_herbs",
      "citrus"
    ]
  }
] as const;

export const GENERATED_CANONICAL_INGREDIENTS = [
  {
    "id": "chicken",
    "catalogId": "chicken",
    "label": "chicken",
    "categoryId": "proteins",
    "subcategoryId": "poultry",
    "aliases": [
      "poultry"
    ],
    "browseNodeIds": [
      "chicken"
    ],
    "recommendationRollupIds": [
      "chicken"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "chicken_breast",
    "catalogId": "chicken_breast",
    "label": "chicken breast",
    "categoryId": "proteins",
    "subcategoryId": "poultry",
    "aliases": [
      "chicken breasts",
      "boneless chicken breast",
      "skinless chicken breast"
    ],
    "browseNodeIds": [
      "chicken"
    ],
    "recommendationRollupIds": [
      "chicken"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "chicken_thighs",
    "catalogId": "chicken_thighs",
    "label": "chicken thighs",
    "categoryId": "proteins",
    "subcategoryId": "poultry",
    "aliases": [
      "chicken thigh"
    ],
    "browseNodeIds": [
      "chicken"
    ],
    "recommendationRollupIds": [
      "chicken"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "ground_chicken",
    "catalogId": "ground_chicken",
    "label": "ground chicken",
    "categoryId": "proteins",
    "subcategoryId": "poultry",
    "aliases": [
      "minced chicken"
    ],
    "browseNodeIds": [
      "chicken"
    ],
    "recommendationRollupIds": [
      "chicken"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "turkey",
    "catalogId": "turkey",
    "label": "turkey",
    "categoryId": "proteins",
    "subcategoryId": "poultry",
    "aliases": [],
    "browseNodeIds": [
      "chicken"
    ],
    "recommendationRollupIds": [
      "chicken"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "ground_turkey",
    "catalogId": "ground_turkey",
    "label": "ground turkey",
    "categoryId": "proteins",
    "subcategoryId": "poultry",
    "aliases": [
      "minced turkey"
    ],
    "browseNodeIds": [
      "chicken"
    ],
    "recommendationRollupIds": [
      "chicken"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "beef",
    "catalogId": "beef",
    "label": "beef",
    "categoryId": "proteins",
    "subcategoryId": "red_meat",
    "aliases": [],
    "browseNodeIds": [
      "beef"
    ],
    "recommendationRollupIds": [
      "beef"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "ground_beef",
    "catalogId": "ground_beef",
    "label": "ground beef",
    "categoryId": "proteins",
    "subcategoryId": "red_meat",
    "aliases": [
      "hamburger meat",
      "beef mince",
      "minced beef",
      "ground chuck"
    ],
    "browseNodeIds": [
      "beef"
    ],
    "recommendationRollupIds": [
      "beef"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "steak",
    "catalogId": "steak",
    "label": "steak",
    "categoryId": "proteins",
    "subcategoryId": "red_meat",
    "aliases": [
      "beef steak",
      "beef strips",
      "thinly sliced steak",
      "sliced steak",
      "beef strip",
      "steak strip",
      "steak strips"
    ],
    "browseNodeIds": [
      "beef"
    ],
    "recommendationRollupIds": [
      "beef"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "pork",
    "catalogId": "pork",
    "label": "pork",
    "categoryId": "proteins",
    "subcategoryId": "red_meat",
    "aliases": [],
    "browseNodeIds": [
      "pork"
    ],
    "recommendationRollupIds": [
      "pork"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "pork_chops",
    "catalogId": "pork_chops",
    "label": "pork chops",
    "categoryId": "proteins",
    "subcategoryId": "red_meat",
    "aliases": [
      "pork chop"
    ],
    "browseNodeIds": [
      "pork"
    ],
    "recommendationRollupIds": [
      "pork"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "sausage",
    "catalogId": "sausage",
    "label": "sausage",
    "categoryId": "proteins",
    "subcategoryId": "red_meat",
    "aliases": [
      "italian sausage",
      "breakfast sausage"
    ],
    "browseNodeIds": [
      "pork"
    ],
    "recommendationRollupIds": [
      "pork"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "bacon",
    "catalogId": "bacon",
    "label": "bacon",
    "categoryId": "proteins",
    "subcategoryId": "red_meat",
    "aliases": [],
    "browseNodeIds": [
      "pork"
    ],
    "recommendationRollupIds": [
      "pork"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "ham",
    "catalogId": "ham",
    "label": "ham",
    "categoryId": "proteins",
    "subcategoryId": "red_meat",
    "aliases": [
      "deli ham"
    ],
    "browseNodeIds": [
      "pork"
    ],
    "recommendationRollupIds": [
      "pork"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "seafood",
    "catalogId": "seafood",
    "label": "seafood",
    "categoryId": "proteins",
    "subcategoryId": "seafood",
    "aliases": [
      "fish"
    ],
    "browseNodeIds": [
      "seafood"
    ],
    "recommendationRollupIds": [
      "seafood"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "shrimp",
    "catalogId": "shrimp",
    "label": "shrimp",
    "categoryId": "proteins",
    "subcategoryId": "seafood",
    "aliases": [
      "prawns"
    ],
    "browseNodeIds": [
      "seafood"
    ],
    "recommendationRollupIds": [
      "seafood"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "salmon",
    "catalogId": "salmon",
    "label": "salmon",
    "categoryId": "proteins",
    "subcategoryId": "seafood",
    "aliases": [],
    "browseNodeIds": [
      "seafood"
    ],
    "recommendationRollupIds": [
      "seafood"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "tuna",
    "catalogId": "tuna",
    "label": "tuna",
    "categoryId": "proteins",
    "subcategoryId": "seafood",
    "aliases": [
      "canned tuna"
    ],
    "browseNodeIds": [
      "seafood"
    ],
    "recommendationRollupIds": [
      "seafood"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "cod",
    "catalogId": "cod",
    "label": "cod",
    "categoryId": "proteins",
    "subcategoryId": "seafood",
    "aliases": [],
    "browseNodeIds": [
      "seafood"
    ],
    "recommendationRollupIds": [
      "seafood"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "tilapia",
    "catalogId": "tilapia",
    "label": "tilapia",
    "categoryId": "proteins",
    "subcategoryId": "seafood",
    "aliases": [],
    "browseNodeIds": [
      "seafood"
    ],
    "recommendationRollupIds": [
      "seafood"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "white_fish",
    "catalogId": "white_fish",
    "label": "white fish",
    "categoryId": "proteins",
    "subcategoryId": "seafood",
    "aliases": [
      "whitefish",
      "bass",
      "sea bass",
      "catfish"
    ],
    "browseNodeIds": [
      "seafood"
    ],
    "recommendationRollupIds": [
      "seafood"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "eggs",
    "catalogId": "eggs",
    "label": "eggs",
    "categoryId": "proteins",
    "subcategoryId": "eggs",
    "aliases": [
      "egg"
    ],
    "browseNodeIds": [
      "eggs"
    ],
    "recommendationRollupIds": [
      "eggs"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "tofu",
    "catalogId": "tofu",
    "label": "tofu",
    "categoryId": "proteins",
    "subcategoryId": "plant_protein",
    "aliases": [
      "firm tofu",
      "extra firm tofu"
    ],
    "browseNodeIds": [
      "tofu_plant_protein"
    ],
    "recommendationRollupIds": [
      "plant_protein"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "edamame",
    "catalogId": "edamame",
    "label": "edamame",
    "categoryId": "proteins",
    "subcategoryId": "plant_protein",
    "aliases": [],
    "browseNodeIds": [
      "tofu_plant_protein"
    ],
    "recommendationRollupIds": [
      "plant_protein"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "beans",
    "catalogId": "beans",
    "label": "beans",
    "categoryId": "proteins",
    "subcategoryId": "plant_protein",
    "aliases": [
      "bean"
    ],
    "browseNodeIds": [
      "beans_legumes"
    ],
    "recommendationRollupIds": [
      "plant_protein"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "black_beans",
    "catalogId": "black_beans",
    "label": "black beans",
    "categoryId": "proteins",
    "subcategoryId": "plant_protein",
    "aliases": [
      "black bean",
      "canned black beans"
    ],
    "browseNodeIds": [
      "beans_legumes"
    ],
    "recommendationRollupIds": [
      "plant_protein"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "white_beans",
    "catalogId": "white_beans",
    "label": "white beans",
    "categoryId": "proteins",
    "subcategoryId": "plant_protein",
    "aliases": [
      "white bean"
    ],
    "browseNodeIds": [
      "beans_legumes"
    ],
    "recommendationRollupIds": [
      "plant_protein"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "pinto_beans",
    "catalogId": "pinto_beans",
    "label": "pinto beans",
    "categoryId": "proteins",
    "subcategoryId": "plant_protein",
    "aliases": [
      "pinto bean"
    ],
    "browseNodeIds": [
      "beans_legumes"
    ],
    "recommendationRollupIds": [
      "plant_protein"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "canned_beans",
    "catalogId": "canned_beans",
    "label": "canned beans",
    "categoryId": "proteins",
    "subcategoryId": "plant_protein",
    "aliases": [
      "canned bean",
      "beans canned"
    ],
    "browseNodeIds": [
      "beans_legumes"
    ],
    "recommendationRollupIds": [
      "plant_protein"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "chickpeas",
    "catalogId": "chickpeas",
    "label": "chickpeas",
    "categoryId": "proteins",
    "subcategoryId": "plant_protein",
    "aliases": [
      "chickpea",
      "garbanzo",
      "garbanzo beans",
      "garbanzo bean",
      "garbanzos"
    ],
    "browseNodeIds": [
      "beans_legumes"
    ],
    "recommendationRollupIds": [
      "plant_protein"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "lentils",
    "catalogId": "lentils",
    "label": "lentils",
    "categoryId": "proteins",
    "subcategoryId": "plant_protein",
    "aliases": [
      "lentil"
    ],
    "browseNodeIds": [
      "beans_legumes"
    ],
    "recommendationRollupIds": [
      "plant_protein"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "rice",
    "catalogId": "rice",
    "label": "rice",
    "categoryId": "grains_starches",
    "subcategoryId": "rice_grains",
    "aliases": [
      "white rice",
      "brown rice",
      "jasmine rice",
      "basmati rice"
    ],
    "browseNodeIds": [
      "rice_grains"
    ],
    "recommendationRollupIds": [
      "grains_starches"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "quinoa",
    "catalogId": "quinoa",
    "label": "quinoa",
    "categoryId": "grains_starches",
    "subcategoryId": "grains",
    "aliases": [],
    "browseNodeIds": [
      "rice_grains"
    ],
    "recommendationRollupIds": [
      "grains_starches"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "couscous",
    "catalogId": "couscous",
    "label": "couscous",
    "categoryId": "grains_starches",
    "subcategoryId": "grains",
    "aliases": [],
    "browseNodeIds": [
      "rice_grains"
    ],
    "recommendationRollupIds": [
      "grains_starches"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "pasta",
    "catalogId": "pasta",
    "label": "pasta",
    "categoryId": "grains_starches",
    "subcategoryId": "pasta_noodles",
    "aliases": [
      "macaroni",
      "linguine",
      "fettuccine",
      "shells",
      "penne",
      "orzo",
      "tortellini",
      "ziti"
    ],
    "browseNodeIds": [
      "pasta_noodles"
    ],
    "recommendationRollupIds": [
      "grains_starches"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "spaghetti",
    "catalogId": "spaghetti",
    "label": "spaghetti",
    "categoryId": "grains_starches",
    "subcategoryId": "pasta_noodles",
    "aliases": [
      "spaghetti noodles"
    ],
    "browseNodeIds": [
      "pasta_noodles"
    ],
    "recommendationRollupIds": [
      "grains_starches"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "noodles",
    "catalogId": "noodles",
    "label": "noodles",
    "categoryId": "grains_starches",
    "subcategoryId": "pasta_noodles",
    "aliases": [
      "lo mein noodles",
      "egg noodles",
      "udon",
      "udon noodles",
      "lo mein",
      "lo mein noodle",
      "rice noodle",
      "rice noodles"
    ],
    "browseNodeIds": [
      "pasta_noodles"
    ],
    "recommendationRollupIds": [
      "grains_starches"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "ramen_noodles",
    "catalogId": "ramen_noodles",
    "label": "ramen noodles",
    "categoryId": "grains_starches",
    "subcategoryId": "pasta_noodles",
    "aliases": [
      "ramen"
    ],
    "browseNodeIds": [
      "pasta_noodles"
    ],
    "recommendationRollupIds": [
      "grains_starches"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "ravioli",
    "catalogId": "ravioli",
    "label": "ravioli",
    "categoryId": "grains_starches",
    "subcategoryId": "pasta_noodles",
    "aliases": [],
    "browseNodeIds": [
      "pasta_noodles"
    ],
    "recommendationRollupIds": [
      "grains_starches"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "bread",
    "catalogId": "bread",
    "label": "bread",
    "categoryId": "grains_starches",
    "subcategoryId": "bread_wraps",
    "aliases": [
      "sliced bread",
      "sandwich bread"
    ],
    "browseNodeIds": [
      "bread_wraps"
    ],
    "recommendationRollupIds": [
      "grains_starches"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "flour_tortillas",
    "catalogId": "flour_tortillas",
    "label": "flour tortillas",
    "categoryId": "grains_starches",
    "subcategoryId": "bread_wraps",
    "aliases": [
      "flour tortilla"
    ],
    "browseNodeIds": [
      "bread_wraps"
    ],
    "recommendationRollupIds": [
      "grains_starches"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "corn_tortillas",
    "catalogId": "corn_tortillas",
    "label": "corn tortillas",
    "categoryId": "grains_starches",
    "subcategoryId": "bread_wraps",
    "aliases": [
      "corn tortilla",
      "tostada",
      "tostadas"
    ],
    "browseNodeIds": [
      "bread_wraps"
    ],
    "recommendationRollupIds": [
      "grains_starches"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "pita",
    "catalogId": "pita",
    "label": "pita",
    "categoryId": "grains_starches",
    "subcategoryId": "bread_wraps",
    "aliases": [],
    "browseNodeIds": [
      "bread_wraps"
    ],
    "recommendationRollupIds": [
      "grains_starches"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "buns",
    "catalogId": "buns",
    "label": "buns",
    "categoryId": "grains_starches",
    "subcategoryId": "bread_wraps",
    "aliases": [
      "burger buns",
      "burger bun",
      "sandwich rolls",
      "sandwich roll",
      "rolls"
    ],
    "browseNodeIds": [
      "bread_wraps"
    ],
    "recommendationRollupIds": [
      "grains_starches"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "breadcrumbs",
    "catalogId": "breadcrumbs",
    "label": "breadcrumbs",
    "categoryId": "grains_starches",
    "subcategoryId": "bread_wraps",
    "aliases": [
      "bread crumbs",
      "panko",
      "panko breadcrumbs"
    ],
    "browseNodeIds": [
      "bread_wraps"
    ],
    "recommendationRollupIds": [
      "grains_starches"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "potatoes",
    "catalogId": "potatoes",
    "label": "potatoes",
    "categoryId": "grains_starches",
    "subcategoryId": "starches",
    "aliases": [
      "potato"
    ],
    "browseNodeIds": [
      "potatoes"
    ],
    "recommendationRollupIds": [
      "grains_starches"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "sweet_potatoes",
    "catalogId": "sweet_potatoes",
    "label": "sweet potatoes",
    "categoryId": "grains_starches",
    "subcategoryId": "starches",
    "aliases": [
      "sweet potato"
    ],
    "browseNodeIds": [
      "potatoes"
    ],
    "recommendationRollupIds": [
      "grains_starches"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "onion",
    "catalogId": "onion",
    "label": "onion",
    "categoryId": "vegetables",
    "subcategoryId": "aromatics",
    "aliases": [
      "yellow onion",
      "white onion",
      "red onion"
    ],
    "browseNodeIds": [
      "aromatics"
    ],
    "recommendationRollupIds": [
      "vegetables"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "garlic",
    "catalogId": "garlic",
    "label": "garlic",
    "categoryId": "vegetables",
    "subcategoryId": "aromatics",
    "aliases": [
      "garlic clove",
      "garlic cloves",
      "minced garlic"
    ],
    "browseNodeIds": [
      "aromatics"
    ],
    "recommendationRollupIds": [
      "vegetables"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "green_onion",
    "catalogId": "green_onion",
    "label": "green onion",
    "categoryId": "vegetables",
    "subcategoryId": "aromatics",
    "aliases": [
      "green onions",
      "scallion",
      "scallions",
      "spring onion",
      "spring onions"
    ],
    "browseNodeIds": [
      "aromatics"
    ],
    "recommendationRollupIds": [
      "vegetables"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "ginger",
    "catalogId": "ginger",
    "label": "ginger",
    "categoryId": "vegetables",
    "subcategoryId": "aromatics",
    "aliases": [
      "fresh ginger"
    ],
    "browseNodeIds": [
      "aromatics"
    ],
    "recommendationRollupIds": [
      "vegetables"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "celery",
    "catalogId": "celery",
    "label": "celery",
    "categoryId": "vegetables",
    "subcategoryId": "aromatics",
    "aliases": [
      "celery stalk",
      "celery stalks"
    ],
    "browseNodeIds": [
      "aromatics"
    ],
    "recommendationRollupIds": [
      "vegetables"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "bell_peppers",
    "catalogId": "bell_pepper",
    "label": "bell peppers",
    "categoryId": "vegetables",
    "subcategoryId": "peppers",
    "aliases": [
      "bell pepper",
      "red bell pepper",
      "green bell pepper",
      "yellow bell pepper",
      "orange bell pepper",
      "capsicum"
    ],
    "browseNodeIds": [
      "peppers_chiles"
    ],
    "recommendationRollupIds": [
      "vegetables"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "jalapenos",
    "catalogId": "jalapenos",
    "label": "jalapenos",
    "categoryId": "vegetables",
    "subcategoryId": "peppers",
    "aliases": [
      "jalapeno"
    ],
    "browseNodeIds": [
      "peppers_chiles"
    ],
    "recommendationRollupIds": [
      "vegetables"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "poblano",
    "catalogId": "poblano",
    "label": "poblano",
    "categoryId": "vegetables",
    "subcategoryId": "peppers",
    "aliases": [
      "poblanos"
    ],
    "browseNodeIds": [
      "peppers_chiles"
    ],
    "recommendationRollupIds": [
      "vegetables"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "green_chiles",
    "catalogId": "green_chiles",
    "label": "green chiles",
    "categoryId": "vegetables",
    "subcategoryId": "peppers",
    "aliases": [
      "green chile"
    ],
    "browseNodeIds": [
      "peppers_chiles"
    ],
    "recommendationRollupIds": [
      "vegetables"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "spinach",
    "catalogId": "spinach",
    "label": "spinach",
    "categoryId": "vegetables",
    "subcategoryId": "greens",
    "aliases": [],
    "browseNodeIds": [
      "leafy_greens"
    ],
    "recommendationRollupIds": [
      "vegetables"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "kale",
    "catalogId": "kale",
    "label": "kale",
    "categoryId": "vegetables",
    "subcategoryId": "greens",
    "aliases": [],
    "browseNodeIds": [
      "leafy_greens"
    ],
    "recommendationRollupIds": [
      "vegetables"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "lettuce",
    "catalogId": "lettuce",
    "label": "lettuce",
    "categoryId": "vegetables",
    "subcategoryId": "greens",
    "aliases": [],
    "browseNodeIds": [
      "leafy_greens"
    ],
    "recommendationRollupIds": [
      "vegetables"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "bok_choy",
    "catalogId": "bok_choy",
    "label": "bok choy",
    "categoryId": "vegetables",
    "subcategoryId": "greens",
    "aliases": [],
    "browseNodeIds": [
      "leafy_greens"
    ],
    "recommendationRollupIds": [
      "vegetables"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "broccoli",
    "catalogId": "broccoli",
    "label": "broccoli",
    "categoryId": "vegetables",
    "subcategoryId": "brassicas",
    "aliases": [],
    "browseNodeIds": [
      "brassicas"
    ],
    "recommendationRollupIds": [
      "vegetables"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "cabbage",
    "catalogId": "cabbage",
    "label": "cabbage",
    "categoryId": "vegetables",
    "subcategoryId": "brassicas",
    "aliases": [],
    "browseNodeIds": [
      "brassicas"
    ],
    "recommendationRollupIds": [
      "vegetables"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "cauliflower",
    "catalogId": "cauliflower",
    "label": "cauliflower",
    "categoryId": "vegetables",
    "subcategoryId": "brassicas",
    "aliases": [],
    "browseNodeIds": [
      "brassicas"
    ],
    "recommendationRollupIds": [
      "vegetables"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "tomato",
    "catalogId": "tomato",
    "label": "tomato",
    "categoryId": "vegetables",
    "subcategoryId": "tomatoes",
    "aliases": [
      "tomatoes",
      "roma tomato"
    ],
    "browseNodeIds": [
      "tomatoes"
    ],
    "recommendationRollupIds": [
      "vegetables"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "cherry_tomatoes",
    "catalogId": "cherry_tomatoes",
    "label": "cherry tomatoes",
    "categoryId": "vegetables",
    "subcategoryId": "tomatoes",
    "aliases": [
      "cherry tomato",
      "grape tomato",
      "grape tomatoes"
    ],
    "browseNodeIds": [
      "tomatoes"
    ],
    "recommendationRollupIds": [
      "vegetables"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "diced_tomatoes",
    "catalogId": "diced_tomatoes",
    "label": "diced tomatoes",
    "categoryId": "vegetables",
    "subcategoryId": "tomatoes",
    "aliases": [
      "canned diced tomatoes"
    ],
    "browseNodeIds": [
      "tomatoes"
    ],
    "recommendationRollupIds": [
      "vegetables"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "crushed_tomatoes",
    "catalogId": "crushed_tomatoes",
    "label": "crushed tomatoes",
    "categoryId": "vegetables",
    "subcategoryId": "tomatoes",
    "aliases": [],
    "browseNodeIds": [
      "tomatoes"
    ],
    "recommendationRollupIds": [
      "vegetables"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "tomato_paste",
    "catalogId": "tomato_paste",
    "label": "tomato paste",
    "categoryId": "vegetables",
    "subcategoryId": "tomatoes",
    "aliases": [],
    "browseNodeIds": [
      "tomatoes"
    ],
    "recommendationRollupIds": [
      "vegetables"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "mushrooms",
    "catalogId": "mushrooms",
    "label": "mushrooms",
    "categoryId": "vegetables",
    "subcategoryId": "mushrooms",
    "aliases": [
      "mushroom"
    ],
    "browseNodeIds": [
      "mushrooms"
    ],
    "recommendationRollupIds": [
      "vegetables"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "lemons",
    "catalogId": "lemons",
    "label": "lemons",
    "categoryId": "vegetables",
    "subcategoryId": "citrus",
    "aliases": [
      "lemon"
    ],
    "browseNodeIds": [
      "citrus"
    ],
    "recommendationRollupIds": [
      "citrus"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "limes",
    "catalogId": "limes",
    "label": "limes",
    "categoryId": "vegetables",
    "subcategoryId": "citrus",
    "aliases": [
      "lime"
    ],
    "browseNodeIds": [
      "citrus"
    ],
    "recommendationRollupIds": [
      "citrus"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "milk",
    "catalogId": "milk",
    "label": "milk",
    "categoryId": "dairy_creamy",
    "subcategoryId": "milk_cream",
    "aliases": [
      "whole milk",
      "2% milk",
      "skim milk"
    ],
    "browseNodeIds": [
      "milk_cream"
    ],
    "recommendationRollupIds": [
      "dairy_creamy"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "cream",
    "catalogId": "cream",
    "label": "cream",
    "categoryId": "dairy_creamy",
    "subcategoryId": "milk_cream",
    "aliases": [
      "heavy cream",
      "half-and-half",
      "half & half"
    ],
    "browseNodeIds": [
      "milk_cream"
    ],
    "recommendationRollupIds": [
      "dairy_creamy"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "sour_cream",
    "catalogId": "sour_cream",
    "label": "sour cream",
    "categoryId": "dairy_creamy",
    "subcategoryId": "milk_cream",
    "aliases": [],
    "browseNodeIds": [
      "milk_cream"
    ],
    "recommendationRollupIds": [
      "dairy_creamy"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "yogurt",
    "catalogId": "yogurt",
    "label": "yogurt",
    "categoryId": "dairy_creamy",
    "subcategoryId": "milk_cream",
    "aliases": [
      "plain yogurt",
      "plain yoghurt"
    ],
    "browseNodeIds": [
      "milk_cream"
    ],
    "recommendationRollupIds": [
      "dairy_creamy"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "cream_cheese",
    "catalogId": "cream_cheese",
    "label": "cream cheese",
    "categoryId": "dairy_creamy",
    "subcategoryId": "milk_cream",
    "aliases": [],
    "browseNodeIds": [
      "milk_cream"
    ],
    "recommendationRollupIds": [
      "dairy_creamy"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "cheese",
    "catalogId": "cheese",
    "label": "cheese",
    "categoryId": "dairy_creamy",
    "subcategoryId": "cheese",
    "aliases": [
      "mixed cheese",
      "sliced cheese",
      "shredded cheese"
    ],
    "browseNodeIds": [
      "cheese"
    ],
    "recommendationRollupIds": [
      "dairy_creamy"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "cheddar",
    "catalogId": "cheddar",
    "label": "cheddar",
    "categoryId": "dairy_creamy",
    "subcategoryId": "cheese",
    "aliases": [
      "cheddar cheese",
      "shredded cheddar"
    ],
    "browseNodeIds": [
      "cheese"
    ],
    "recommendationRollupIds": [
      "dairy_creamy"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "mozzarella",
    "catalogId": "mozzarella",
    "label": "mozzarella",
    "categoryId": "dairy_creamy",
    "subcategoryId": "cheese",
    "aliases": [
      "mozzarella cheese",
      "shredded mozzarella"
    ],
    "browseNodeIds": [
      "cheese"
    ],
    "recommendationRollupIds": [
      "dairy_creamy"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "parmesan",
    "catalogId": "parmesan",
    "label": "parmesan",
    "categoryId": "dairy_creamy",
    "subcategoryId": "cheese",
    "aliases": [
      "parmesan cheese"
    ],
    "browseNodeIds": [
      "cheese"
    ],
    "recommendationRollupIds": [
      "dairy_creamy"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "feta",
    "catalogId": "feta",
    "label": "feta",
    "categoryId": "dairy_creamy",
    "subcategoryId": "cheese",
    "aliases": [
      "feta cheese"
    ],
    "browseNodeIds": [
      "cheese"
    ],
    "recommendationRollupIds": [
      "dairy_creamy"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "butter",
    "catalogId": "butter",
    "label": "butter",
    "categoryId": "dairy_creamy",
    "subcategoryId": "milk_cream",
    "aliases": [
      "salted butter",
      "unsalted butter"
    ],
    "browseNodeIds": [
      "oils_fats"
    ],
    "recommendationRollupIds": [
      "oils_fats"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "salt",
    "catalogId": "salt",
    "label": "salt",
    "categoryId": "herbs_spices",
    "subcategoryId": "dry_spices",
    "aliases": [
      "sea salt",
      "kosher salt",
      "table salt"
    ],
    "browseNodeIds": [
      "dry_spices"
    ],
    "recommendationRollupIds": [
      "herbs_spices"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "black_pepper",
    "catalogId": "black_pepper",
    "label": "black pepper",
    "categoryId": "herbs_spices",
    "subcategoryId": "dry_spices",
    "aliases": [
      "ground pepper",
      "pepper"
    ],
    "browseNodeIds": [
      "dry_spices"
    ],
    "recommendationRollupIds": [
      "herbs_spices"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "garlic_powder",
    "catalogId": "garlic_powder",
    "label": "garlic powder",
    "categoryId": "herbs_spices",
    "subcategoryId": "dry_spices",
    "aliases": [],
    "browseNodeIds": [
      "dry_spices"
    ],
    "recommendationRollupIds": [
      "herbs_spices"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "onion_powder",
    "catalogId": "onion_powder",
    "label": "onion powder",
    "categoryId": "herbs_spices",
    "subcategoryId": "dry_spices",
    "aliases": [],
    "browseNodeIds": [
      "dry_spices"
    ],
    "recommendationRollupIds": [
      "herbs_spices"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "paprika",
    "catalogId": "paprika",
    "label": "paprika",
    "categoryId": "herbs_spices",
    "subcategoryId": "dry_spices",
    "aliases": [],
    "browseNodeIds": [
      "dry_spices"
    ],
    "recommendationRollupIds": [
      "herbs_spices"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "smoked_paprika",
    "catalogId": "smoked_paprika",
    "label": "smoked paprika",
    "categoryId": "herbs_spices",
    "subcategoryId": "dry_spices",
    "aliases": [],
    "browseNodeIds": [
      "dry_spices"
    ],
    "recommendationRollupIds": [
      "herbs_spices"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "chili_powder",
    "catalogId": "chili_powder",
    "label": "chili powder",
    "categoryId": "herbs_spices",
    "subcategoryId": "dry_spices",
    "aliases": [],
    "browseNodeIds": [
      "dry_spices"
    ],
    "recommendationRollupIds": [
      "herbs_spices"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "cumin",
    "catalogId": "cumin",
    "label": "cumin",
    "categoryId": "herbs_spices",
    "subcategoryId": "dry_spices",
    "aliases": [
      "ground cumin"
    ],
    "browseNodeIds": [
      "dry_spices"
    ],
    "recommendationRollupIds": [
      "herbs_spices"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "oregano",
    "catalogId": "oregano",
    "label": "oregano",
    "categoryId": "herbs_spices",
    "subcategoryId": "dry_spices",
    "aliases": [
      "dried oregano",
      "italian seasoning"
    ],
    "browseNodeIds": [
      "dry_spices"
    ],
    "recommendationRollupIds": [
      "herbs_spices"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "curry_powder",
    "catalogId": "curry_powder",
    "label": "curry powder",
    "categoryId": "herbs_spices",
    "subcategoryId": "dry_spices",
    "aliases": [],
    "browseNodeIds": [
      "dry_spices"
    ],
    "recommendationRollupIds": [
      "herbs_spices"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "red_pepper_flakes",
    "catalogId": "red_pepper_flakes",
    "label": "red pepper flakes",
    "categoryId": "herbs_spices",
    "subcategoryId": "dry_spices",
    "aliases": [],
    "browseNodeIds": [
      "dry_spices"
    ],
    "recommendationRollupIds": [
      "herbs_spices"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "cilantro",
    "catalogId": "cilantro",
    "label": "cilantro",
    "categoryId": "herbs_spices",
    "subcategoryId": "fresh_herbs",
    "aliases": [
      "coriander"
    ],
    "browseNodeIds": [
      "fresh_herbs"
    ],
    "recommendationRollupIds": [
      "herbs_spices"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "parsley",
    "catalogId": "parsley",
    "label": "parsley",
    "categoryId": "herbs_spices",
    "subcategoryId": "fresh_herbs",
    "aliases": [],
    "browseNodeIds": [
      "fresh_herbs"
    ],
    "recommendationRollupIds": [
      "herbs_spices"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "basil",
    "catalogId": "basil",
    "label": "basil",
    "categoryId": "herbs_spices",
    "subcategoryId": "fresh_herbs",
    "aliases": [],
    "browseNodeIds": [
      "fresh_herbs"
    ],
    "recommendationRollupIds": [
      "herbs_spices"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "broth",
    "catalogId": "broth",
    "label": "broth",
    "categoryId": "sauces_condiments",
    "subcategoryId": "sauces",
    "aliases": [],
    "browseNodeIds": [
      "sauces"
    ],
    "recommendationRollupIds": [
      "sauces_condiments"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "chicken_broth",
    "catalogId": "chicken_broth",
    "label": "chicken broth",
    "categoryId": "sauces_condiments",
    "subcategoryId": "sauces",
    "aliases": [
      "chicken stock"
    ],
    "browseNodeIds": [
      "sauces"
    ],
    "recommendationRollupIds": [
      "sauces_condiments"
    ],
    "visibility": "search_only"
  },
  {
    "id": "beef_broth",
    "catalogId": "beef_broth",
    "label": "beef broth",
    "categoryId": "sauces_condiments",
    "subcategoryId": "sauces",
    "aliases": [
      "beef stock"
    ],
    "browseNodeIds": [
      "sauces"
    ],
    "recommendationRollupIds": [
      "sauces_condiments"
    ],
    "visibility": "search_only"
  },
  {
    "id": "vegetable_broth",
    "catalogId": "vegetable_broth",
    "label": "vegetable broth",
    "categoryId": "sauces_condiments",
    "subcategoryId": "sauces",
    "aliases": [
      "vegetable stock",
      "veggie broth",
      "veggie stock"
    ],
    "browseNodeIds": [
      "sauces"
    ],
    "recommendationRollupIds": [
      "sauces_condiments"
    ],
    "visibility": "search_only"
  },
  {
    "id": "stock",
    "catalogId": "stock",
    "label": "stock",
    "categoryId": "sauces_condiments",
    "subcategoryId": "sauces",
    "aliases": [],
    "browseNodeIds": [
      "sauces"
    ],
    "recommendationRollupIds": [
      "sauces_condiments"
    ],
    "visibility": "search_only"
  },
  {
    "id": "tomato_sauce",
    "catalogId": "tomato_sauce",
    "label": "tomato sauce",
    "categoryId": "sauces_condiments",
    "subcategoryId": "sauces",
    "aliases": [],
    "browseNodeIds": [
      "sauces"
    ],
    "recommendationRollupIds": [
      "sauces_condiments"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "soy_sauce",
    "catalogId": "soy_sauce",
    "label": "soy sauce",
    "categoryId": "sauces_condiments",
    "subcategoryId": "sauces",
    "aliases": [],
    "browseNodeIds": [
      "sauces"
    ],
    "recommendationRollupIds": [
      "sauces_condiments"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "hot_sauce",
    "catalogId": "hot_sauce",
    "label": "hot sauce",
    "categoryId": "sauces_condiments",
    "subcategoryId": "sauces",
    "aliases": [],
    "browseNodeIds": [
      "sauces"
    ],
    "recommendationRollupIds": [
      "sauces_condiments"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "mustard",
    "catalogId": "mustard",
    "label": "mustard",
    "categoryId": "sauces_condiments",
    "subcategoryId": "sauces",
    "aliases": [
      "yellow mustard",
      "dijon mustard"
    ],
    "browseNodeIds": [
      "sauces"
    ],
    "recommendationRollupIds": [
      "sauces_condiments"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "mayo",
    "catalogId": "mayo",
    "label": "mayo",
    "categoryId": "sauces_condiments",
    "subcategoryId": "sauces",
    "aliases": [
      "mayonnaise"
    ],
    "browseNodeIds": [
      "sauces"
    ],
    "recommendationRollupIds": [
      "sauces_condiments"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "bbq_sauce",
    "catalogId": "bbq_sauce",
    "label": "bbq sauce",
    "categoryId": "sauces_condiments",
    "subcategoryId": "sauces",
    "aliases": [
      "barbecue sauce"
    ],
    "browseNodeIds": [
      "sauces"
    ],
    "recommendationRollupIds": [
      "sauces_condiments"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "salsa",
    "catalogId": "salsa",
    "label": "salsa",
    "categoryId": "sauces_condiments",
    "subcategoryId": "regional_sauces",
    "aliases": [],
    "browseNodeIds": [
      "regional_sauces_pastes"
    ],
    "recommendationRollupIds": [
      "regional_sauces_pastes"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "pesto",
    "catalogId": "pesto",
    "label": "pesto",
    "categoryId": "sauces_condiments",
    "subcategoryId": "regional_sauces",
    "aliases": [],
    "browseNodeIds": [
      "regional_sauces_pastes"
    ],
    "recommendationRollupIds": [
      "regional_sauces_pastes"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "marinara",
    "catalogId": "marinara",
    "label": "marinara",
    "categoryId": "sauces_condiments",
    "subcategoryId": "regional_sauces",
    "aliases": [
      "marinara sauce",
      "pasta sauce"
    ],
    "browseNodeIds": [
      "regional_sauces_pastes"
    ],
    "recommendationRollupIds": [
      "regional_sauces_pastes"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "enchilada_sauce",
    "catalogId": "enchilada_sauce",
    "label": "enchilada sauce",
    "categoryId": "sauces_condiments",
    "subcategoryId": "regional_sauces",
    "aliases": [
      "red enchilada sauce",
      "green enchilada sauce"
    ],
    "browseNodeIds": [
      "regional_sauces_pastes"
    ],
    "recommendationRollupIds": [
      "regional_sauces_pastes"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "teriyaki_sauce",
    "catalogId": "teriyaki_sauce",
    "label": "teriyaki sauce",
    "categoryId": "sauces_condiments",
    "subcategoryId": "sauces",
    "aliases": [],
    "browseNodeIds": [
      "sauces"
    ],
    "recommendationRollupIds": [
      "sauces_condiments"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "sriracha",
    "catalogId": "sriracha",
    "label": "sriracha",
    "categoryId": "sauces_condiments",
    "subcategoryId": "sauces",
    "aliases": [],
    "browseNodeIds": [
      "sauces"
    ],
    "recommendationRollupIds": [
      "sauces_condiments"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "worcestershire_sauce",
    "catalogId": "worcestershire_sauce",
    "label": "worcestershire sauce",
    "categoryId": "sauces_condiments",
    "subcategoryId": "sauces",
    "aliases": [
      "worcestershire"
    ],
    "browseNodeIds": [
      "sauces"
    ],
    "recommendationRollupIds": [
      "sauces_condiments"
    ],
    "visibility": "search_only"
  },
  {
    "id": "ketchup",
    "catalogId": "ketchup",
    "label": "ketchup",
    "categoryId": "sauces_condiments",
    "subcategoryId": "sauces",
    "aliases": [],
    "browseNodeIds": [
      "sauces"
    ],
    "recommendationRollupIds": [
      "sauces_condiments"
    ],
    "visibility": "search_only"
  },
  {
    "id": "peanut_butter",
    "catalogId": "peanut_butter",
    "label": "peanut butter",
    "categoryId": "sauces_condiments",
    "subcategoryId": "sauces",
    "aliases": [],
    "browseNodeIds": [
      "sauces"
    ],
    "recommendationRollupIds": [
      "sauces_condiments"
    ],
    "visibility": "search_only"
  },
  {
    "id": "oil",
    "catalogId": "oil",
    "label": "oil",
    "categoryId": "sauces_condiments",
    "subcategoryId": "oils_fats",
    "aliases": [
      "cooking oil",
      "vegetable oil",
      "canola oil"
    ],
    "browseNodeIds": [
      "oils_fats"
    ],
    "recommendationRollupIds": [
      "oils_fats"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "olive_oil",
    "catalogId": "olive_oil",
    "label": "olive oil",
    "categoryId": "sauces_condiments",
    "subcategoryId": "oils_fats",
    "aliases": [
      "extra virgin olive oil"
    ],
    "browseNodeIds": [
      "oils_fats"
    ],
    "recommendationRollupIds": [
      "oils_fats"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "sesame_oil",
    "catalogId": "sesame_oil",
    "label": "sesame oil",
    "categoryId": "sauces_condiments",
    "subcategoryId": "oils_fats",
    "aliases": [
      "toasted sesame oil"
    ],
    "browseNodeIds": [
      "oils_fats"
    ],
    "recommendationRollupIds": [
      "oils_fats"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "vinegar",
    "catalogId": "vinegar",
    "label": "vinegar",
    "categoryId": "sauces_condiments",
    "subcategoryId": "oils_fats",
    "aliases": [
      "white vinegar"
    ],
    "browseNodeIds": [
      "oils_fats"
    ],
    "recommendationRollupIds": [
      "oils_fats"
    ],
    "visibility": "search_only"
  },
  {
    "id": "miso",
    "catalogId": "miso",
    "label": "miso",
    "categoryId": "sauces_condiments",
    "subcategoryId": "regional_sauces",
    "aliases": [
      "miso paste"
    ],
    "browseNodeIds": [
      "regional_sauces_pastes"
    ],
    "recommendationRollupIds": [
      "regional_sauces_pastes"
    ],
    "visibility": "browse_and_search"
  },
  {
    "id": "salsa_verde",
    "catalogId": "salsa_verde",
    "label": "salsa verde",
    "categoryId": "sauces_condiments",
    "subcategoryId": "regional_sauces",
    "aliases": [],
    "browseNodeIds": [
      "regional_sauces_pastes"
    ],
    "recommendationRollupIds": [
      "regional_sauces_pastes"
    ],
    "visibility": "browse_and_search"
  }
] as const;
